name: bpf-ci

on:
  pull_request:
  push:
    branches:
      - yurinnick-cache-test

env:
  veristat_arch: x86_64
  veristat_toolchain: gcc

concurrency:
  group: ci-test-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/cache@v3
        with:
          key: ${{ env.CACHE_RESULT_KEY }}
          restore-keys: |
            ${{ env.CACHE_RESULT_KEY }}-
          path: /tmp/work/bpf/bpf/veristat-meta
        env:
          CACHE_RESULT_KEY: x86_64-gcc-baseline-veristat-meta

      - name: Print veristat cache
        shell: bash
        run: cat x86_64-gcc-baseline-veristat-meta

      - name: Show veristat comparison
        shell: bash
        run: ./.github/scripts/compare-veristat-results.sh
        env:
          CACHE_RESULT_KEY: x86_64-gcc-baseline-veristat-meta
          VERISTAT_OUTPUT: x86_64-gcc-baseline-veristat-meta
